### PR TITLE
Added "Quasar Framework V1 Course Preview" YouTube playlist

### PR DESCRIPTION
**Pull request by fruitangdan**
Added "Quasar Framework V1 Course Preview" YouTube playlist

### CODE REVIEW

**Comment by rstoenescu** [comment]
Nice!! Thanks for sharing!

**Comment by rstoenescu** [comment]
Tweeted about it.

**Comment by fruitangdan** [comment]
Thanks man!

**Comment by rstoenescu** [comment]
Go go go :)

**Pull request merged**
