### PR TITLE
Add MyClinic web/mobile app.

### PR DESCRIPTION
**Pull request by steveclarke**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thank you!
Can't access the web page though.

**Comment by steveclarke** [comment]
ok thanks! I'll look into the web page issue. Are you getting an error of
any type?

*Steve Clarke* *//* *SEVENVIEW STUDIOS*
*----------------------------------------------*

Tel. 709.700.0031 x101 // Toll Free (888) 488-0819
<%28888%29%20488-0819%20%C2%A0ext.101>
steve@sevenview.ca // https://www.sevenview.ca
​@sevenviewsteve // fb.com/sevenviewstudios​

**Comment by rstoenescu** [comment]
Sounds like DNS needed to update. All good now.
But, the website section is for websites built with Quasar only :)

**Comment by steveclarke** [comment]
Ah ok, I had both the main website (www.myclinic.today) and the web app (app.myclinic.toay) linked in that section. You can remove just the "info" website and keep the app one. If you'd like me to submit a new pull request with just the web app linked let me know.

**Comment by rstoenescu** [comment]
It's ok. Did the updates already. Thank you for submitting!

**Pull request merged**
