### PR TITLE
Our projects that Proudly using Qausar

### PR DESCRIPTION
**Pull request by kakajan**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks for sharing!

**Comment by kakajan** [comment]
It is my pleasure.
Thanks for your great job dear Razvan 🌹❤

**Comment by dmitry** [comment]
@kakajan please check https://api.oipipe.com/api/global/product/ -> type some numbers. You will see ENV variables are visible because php error page shown with too many details.

**Comment by kakajan** [comment]
Thank your dear @dmitry 
Debugging mode was enabled.
I fixed it.
Thank you again

**Pull request merged**
