### PR TITLE
Adding Dashblocks Template

### PR DESCRIPTION
**Pull request by sv2**
Adding Dashblocks Template under "Projects Using Quasar"

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks for sharing!
Mind you that the deployment needs the publicPath to be `/dashblocks-template/` otherwise the links won't work correctly.

**Comment by sv2** [comment]
Thanks a lot for accepting ! Will add a note about publicPath to Readme 
Many thanks for your work on amazing Quasar Framework !

**Comment by rstoenescu** [comment]
No, I mean deploy it with that. The demo site doesn’t works correctly otherwise.

**Comment by sv2** [comment]
Got it. Have `publicPath: '/dashblocks-template/'` set up in `vue.config.js`, as I am using `vue-cli-plugin-quasar`. Demo site published on GH pages at https://slanatech.github.io/dashblocks-template/
Thank you

**Comment by rstoenescu** [comment]
Highly recommend the Quasar CLI for the absolute best experience with Quasar.

**Pull request merged**
