### PR TITLE
Added Boid.com

### PR DESCRIPTION
**Pull request by Boid-John**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thank you so much for sharing!

**Comment by rstoenescu** [comment]
Awesome work, btw!

**Comment by Boid-John** [comment]
Thanks @rstoenescu we are huge fans of Quasar!

**Comment by aaronk1977** [comment]
Thank you and that you have I saved your problems this is Aaron Daniel Kaatz Romeo L from Texas you

**Pull request merged**
